### PR TITLE
narrator and singing voices

### PR DESCRIPTION
**Pull request by DetachHead**

### CODE REVIEW

**Comment by bulieme** [comment]
Bro thank you

**Comment by oscie57** [comment]
holy crap thank you so much! if you could add the singing voices to CODES.md, then I will merge right away. this is so useful you dont even understand tysm

**Comment by DetachHead** [comment]
@oscie57 done

**Comment by KotlinIsland** [comment]
Could you add "amongus imposter" by any chance?

I think I will actually block this 'Merge Request' (alt git dog whistle) until you add the sussy amongus voice.

**Comment by DetachHead** [comment]
Unfortunately amongus is censored in china so we are can't add the amongus voice

**Pull request merged**
