### PR TITLE
Fixed TTS using headers

### PR DESCRIPTION
**Pull request by AdamAtomus**
You now need to authenticate with a sessionid generated by the app.

### CODE REVIEW

**Comment by oscie57** [comment]
oh my god you are a legend

**Comment by oscie57** [comment]
i have no idea how, if someone could write up how it works i can add a wiki

**Comment by GnomedDev** [comment]
How did you acquire this info? I've been trying to MITM for a while and cannot seem to certificate unpin.

**Comment by AdamAtomus** [comment]
> This is great but it would be nice if there was a guide/tutorial on how to generate your own session id in the future

Yeah, you can get one using an emulator + [httptoolkit](https://httptoolkit.tech/android/)
someone says you need to use [frida](https://github.com/httptoolkit/frida-android-unpinning) but it gives me the same sessionid.

**Comment by matty45** [comment]
I'm glad it could be done in an emulator, not fond of putting that app on my actual phone

**Comment by matty45** [comment]
> > This is great but it would be nice if there was a guide/tutorial on how to generate your own session id in the future
> 
> Yeah, you can get one using an emulator + [httptoolkit](https://httptoolkit.tech/android/) someone says you need to use [frida](https://github.com/httptoolkit/frida-android-unpinning) but it gives me the same sessionid.

What emulator do you use?

**Comment by AdamAtomus** [comment]
> > > This is great but it would be nice if there was a guide/tutorial on how to generate your own session id in the future
> > 
> > 
> > Yeah, you can get one using an emulator + [httptoolkit](https://httptoolkit.tech/android/) someone says you need to use [frida](https://github.com/httptoolkit/frida-android-unpinning) but it gives me the same sessionid.
> 
> What emulator do you use?

nox

**Comment by matty45** [comment]
I've tried genymotion and android-86 to no avail

**Comment by hugeblank** [comment]
Permission to yoink and twist this for my shell script?

**Comment by AdamAtomus** [comment]
> Permission to yoink and twist this for [my shell script](https://gist.github.com/hugeblank/6c59ae6ea24f908d249f754141971e4f)?

not stopping you :) though you should use your own sessionid

**Comment by hugeblank** [comment]
Thanks! I'll be looking into a way to get the session id directly through the command line as well. Will share any progress I have with that on discord.

**Pull request merged**
